fn_args_density = "Vertical"
fn_brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
fn_single_line = true
item_brace_style = "AlwaysNextLine"
match_block_trailing_comma = true
spaces_within_parens = true
